experiment:
  # It contains all the about the grids and the group of runs:
  name: SARTFusion # name of the logger platform experiment
  group: EfficientDet # name of group of experiments for the logger platform
  continue_with_errors: False # continue with other runs even if a run fails
  start_from_grid: 0 # skip grids in the grid search
  start_from_run: 0 # skip runs from the selected grid
  search: grid
  # n_trials: 5

parameters:
  # Contains the parameters to build the grid.
  # Each value should be a dict or a list
  seed: &seed [42] # random seed to set
  task: [detection] # task to perform

  tracker:
    ignored_files: ["*.bin,*.safetensors"]
    val_image_log_frequency: [30]

  train:
    max_epochs: [500]
    compile: [False]
    initial_lr: [0.001]
    optimizer: [AdamW]
    watch_metric: [map]
  
  loss:

  model:
    name: [effdet]
    params:
      num_classes: [6]
      image_size: [512]

  dataset: # parameters depending on the class you defined for the dataset
    name: [wisard] 
    root: [dataset/WiSARD]
    preprocessor:
      mean: [[0.485, 0.456, 0.406]]
      std: [[0.229, 0.224, 0.225]]
    folders: [vis]
    image_size: [512]

  dataloader:
    num_workers: [0]
    batch_size: [2]
  
  # train_evaluation: # evaluation during training
  val_evaluation: # evaluation during validation
    metrics: # no extra metrics except standard evaluator

other_grids:
