experiment:
  # It contains all the about the grids and the group of runs:
  name: SARTFusion # name of the logger platform experiment
  group: SARDPose # name of group of experiments for the logger platform
  continue_with_errors: False # continue with other runs even if a run fails
  start_from_grid: 0 # skip grids in the grid search
  start_from_run: 0 # skip runs from the selected grid
  search: grid
  # n_trials: 5

parameters:
  # Contains the parameters to build the grid.
  # Each value should be a dict or a list
  seed: &seed [42] # random seed to set

  tracker:
    ignored_files: ["*.bin,*.safetensors"]

  train:
    max_epochs: [50]
    compile: [False]
    initial_lr: [0.0001]
    optimizer: [AdamW]
    watch_metric: [F1Score]
  
  loss:
    name: [yolo_loss]
    params:
      requires_model: [True]
      cls_pw: [1.0]
      fl_gamma: [0.0]
  
  model:
    name: [yolov9]
    params:
      cfg: [cfg/yolov9-c.yaml]
      # checkpoint: [checkpoints/yolov9-c-converted.pt]

  dataset: # parameters depending on the class you defined for the dataset
    name: [wisard] 
    root: [dataset/WiSARD]
    preprocessor:
      mean: [0.485, 0.456, 0.406] 
      std: [0.229, 0.224, 0.225]
    folders: [vis]
    image_size: [640]

  dataloader:
    num_workers: [0]
    batch_size: [2]
  
  train_metrics:
  val_metrics:

other_grids:
