#!/bin/bash

#SBATCH -A IscrC_DELIGHT
#SBATCH -p boost_usr_prod
#SBATCH --qos normal
#SBATCH --time 24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=123000
#SBATCH --job-name=simplify_wisard
#SBATCH --out=simplify_wisard.out
#SBATCH --err=simplify_wisard.out

srun ./slurm/simplify_wisard_exe $@