experiment:
  # It contains all the about the grids and the group of runs:
  name: SARTFusion # name of the logger platform experiment
  group: SARDPose # name of group of experiments for the logger platform
  continue_with_errors: False # continue with other runs even if a run fails
  start_from_grid: 0 # skip grids in the grid search
  start_from_run: 0 # skip runs from the selected grid
  search: grid
  # n_trials: 5

parameters:
  # Contains the parameters to build the grid.
  # Each value should be a dict or a list
  seed: &seed [42] # random seed to set

  tracker:
    ignored_files: ["*.bin,*.safetensors"]

  train:
    max_epochs: [50]
    compile: [False]
    initial_lr: [0.0001, 0.00005, 0.00001]
    optimizer: [AdamW]
    watch_metric: [F1Score]
    freeze_backbone: [True, False]
  
  loss:
    name: [CrossEntropyLoss]
    params:
  
  model:
    name: [vit_classifier]
    params:
      path: &model_path [google/vit-base-patch16-224]
      labels: 
        - - running
          - walking
          - laying_down
          - not_defined
          - seated
          - stands

  dataset: # parameters depending on the class you defined for the dataset
    name: [sard_pose] 
    root: [dataset/sard_pose]
    preprocessor:
      path: *model_path

  dataloader:
    num_workers: [8]
    batch_size: [16]
  
  train_evaluation:
    metrics:
      Accuracy: &metric_params
        num_classes: [6]
        task: [multiclass]
        average: [macro]
      F1Score: *metric_params
  val_evaluation:
    metrics:
      Accuracy: *metric_params
      F1Score: *metric_params
      Precision: *metric_params
      Recall: *metric_params
      ConfusionMatrix:
        num_classes: [6]
        task: [multiclass]

other_grids:
